### ISSUE TITLE
Examples or implementation help

### ISSUE THREAD

**Issue by eiktyrner** [infinum/mobx-jsonapi-store#1]
Are there any example projects using this or could you show a bit more on how to implement this in an application? I'm not sure how I would use this to render an `@observable` in a component for example?

**Comment by DarkoKukovec** [comment]
Hi @eiktyrner 
We're using this library on a project, but unfortunately, it's not open-source. Here are some examples instead:

First, you need to initialize the store (I'm using the most basic store options here):

``` javascript
// store.js
export default new JsonApiStore();
```

Then, in your component, you'll need to get the store. You can do this in three ways:
1. Including it directly in the component - ok for a small app and is the simplest
2. Include it in your app or container component and pass it as a prop to the component where you want to use it -  might be better suited if you're building something more complex
3. Use the `Provider` and `inject` from `mobx-react` in order to get the store to your component - most complicated one, but it's the only option if you want to use server-side rendering

Also, the component where you're using the store should have the `@observer` decorator.

Once you update the store, your component will automatically be updated if it depended on something that has changed. If your component is not beeing updated, make sure you're using either the store directly or through a computed value. Also, the component will not be updated if you're accessing the data in some other component method and not in the render method.

This is ok:

``` javascript
import store from './store';
import React, {Component} from 'react';
import Todo from './Todo';
import {observer} from 'mobx-react';

@observer
export default class TodoList extends Component {
  render() {
    const todos = store.findAll('todo');

    return (
      <div>
        {todos.map((todo) => <Todo key={todo.id} item={todo} />)
      </div>
    );
  }
}
```

This won't work (it will only be calculated on mount):

``` javascript
import store from './store';
import React, {Component} from 'react';
import Todo from './Todo';
import {observer} from 'mobx-react';

@observer
export default class TodoList extends Component {
  componentWillMount() {
    this.todos = store.findAll('todo');
  }
  render() {
    return (
      <div>
        {this.todos.map((todo) => <Todo key={todo.id} item={todo} />)
      </div>
    );
  }
}
```

An example of updating the store:

``` javascript
import store from './store';

export default async function getTodos() {
  const res = await fetch('/todos');
  const data = await res.json();
  return store.sync(data); // This will also return the received models - in this case an array of todos
}
```

**Comment by eiktyrner** [comment]
Thanks for explaining, that really helps!
