### ISSUE TITLE
Extending Store class breaks in multiple stores pattern

### ISSUE THREAD

**Issue by kapso** [infinum/mobx-jsonapi-store#100]
I am new to mobx and this library, and trying to follow this pattern for multiple stores - `Combining multiple stores` (scroll to bottom) https://mobx.js.org/best/store.html

While doing so I get the following error when I do - `const rootStore = new RootStore();`
```
mobx.module.js:119 Uncaught Error: [mobx] Passing a 'computed' as initial property value is no longer supported by extendObservable. Use a getter or decorator instead
    at invariant$$1 (mobx.module.js:119)
    at fail$$1 (mobx.module.js:114)
    at extendObservableObjectWithProperties$$1 (mobx.module.js:2496)
    at Module.extendObservable$$1 (mobx.module.js:2472)
    at UserStore.Collection (Collection.js:78)
    at UserStore.NetworkStore [as constructor] (NetworkStore.js:43)
    at UserStore.Store [as constructor] (Store.js:61)
    at new UserStore (UserStore.js:6)
    at new RootStore (RootStore.js:7)
    at Module../app/javascript/dashboard/components/containers/App.jsx (App.jsx:12)
```

Class definitions:
```javascript
// RootStore.js
export default class RootStore {
  constructor() {
    this.userStore = new UserStore(this);
  }
}

// UserStore.js
export default class UserStore extends Store {
  constructor(rootStore) {
    super();
    this.rootStore = rootStore;
  }
}
```

Library versions:
```
"mobx": "^5.9.0",
"mobx-jsonapi-store": "^4.4.0",
"mobx-react": "5.4.3",
"react": "^16.8.3",
```

**Comment by DarkoKukovec** [comment]
Hi @kapso 

`mobx-jsonapi-store` was writen for MobX 3 and by the time MobX 4 came out, we had a better idea of our needs and since it wasn't trivial to maintain MobX 3 and 4 compatibility, we decided to create a more future-proof library:

https://github.com/infinum/datx - DatX supports both MobX 4 and 5, has better support for TypeScript ([although not mandatory](https://github.com/infinum/datx/wiki/Defining-models#option-1)) and plugins/mixins while keeping the similar concepts as mobx-jsonapi-store.
There are [examples](https://github.com/infinum/datx/tree/master/examples/datx-jsonapi) in how to set it up, and [migration guide from mobx-jsonapi-store](https://github.com/infinum/datx/wiki/Migration-from-mobx-jsonapi-store) in case you already did some significant work with it.

**Comment by kapso** [comment]
Thanks @DarkoKukovec
