### ISSUE TITLE
Multiple baseUrls

### ISSUE THREAD

**Issue by jgillich** [infinum/mobx-jsonapi-store#25]
To be honest, relying on ES6 module caching for configuration seems like a really bad idea. It also doesn't allow for multiple baseUrls, right? As in one record from url X and another record from url Y.

**Comment by DarkoKukovec** [comment]
Hi @jgillich,
why do you think ES6 module caching is a bad idea? Is there an issue I'm not aware of?
The alternative would be to define the baseUrl on the Store, but there are not many advantages for this since the goal is to have a single store for all the data. This also wouldn't help with the multiple baseUrls either.

The idea of this lib is to follow the JSON API standard and have some sane defaults (e.g. all API calls on the same url), but it was also made extendable, so it should be possible to change pretty much everything you need so you can adapt it for your needs.

If you need a different baseUrl per type, you have two options:
1. Leave the config baseUrl empty, but define the model baseUrl
2. Plug in somewhere in the process. If you think it would be useful, the `NetworkStore.__prefixUrl` method could be made public so it can be overriden (it could also get more arguments, like the model)
