### ISSUE TITLE
Create a new record with relationships

### ISSUE THREAD

**Issue by aldarund** [infinum/mobx-jsonapi-store#47]
How to create a new record with relationships to execute post request using save method that will result to a json like in specs http://jsonapi.org/format/#crud-creating ? 
I see a method saveRelationship but it as i understand will execute request right away and is for updating, while im looking for creating a new record with relationships and save it.

**Comment by aldarund** [comment]
Nevermind, i must be blind. There is assignRef function. And i somehow missed it when reading docs, and only found when i digged into sources :)
Although refs property of custom record can have some docs, because its only appears once in example without real explanation how it works\how to use it

**Comment by DarkoKukovec** [comment]
Hi @aldarund 

I'm aware that the current documentation is bad and almost non-existing. I'm working on a new version that should better document all options and also give examples for some specific use cases. In the meantime, you might try with the [mobx-collection-store](https://github.com/infinum/mobx-collection-store/wiki) docs. Since JsonAPI store is build on top of it, it might be helpful.
