### ISSUE TITLE
Dirty tracking?

### ISSUE THREAD

**Issue by swrobel** [infinum/mobx-jsonapi-store#75]
This may be a feature request, as I looked through the code and couldn't find any evidence of support.

Scenario:
1. Fetch a record from the server
1. Modify some (but not all) attributes of that record
1. Save that record back to the server

Does the PATCH request include all attributes of the record, or only those that have been modified?

**Comment by DarkoKukovec** [comment]
Hi @swrobel, you're correct - this feature is not implemented. Is this something that should be supported, since the specification says it doesn't matter if the whole object is sent or just some properties:
> Any or all of a resource’s attributes MAY be included in the resource object included in a PATCH request.
> If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values.

I realize this would mean less data to be sent, but it increases complexity (potentially new bugs where the wrong attributes are sent) and it would have influence on the performance (higher memory usage - need to keep two versions of a record).

**Comment by swrobel** [comment]
Wouldn't using [viewModel](https://github.com/mobxjs/mobx-utils#viewmodel) give you dirty tracking essentially "for free"?

**Comment by DarkoKukovec** [comment]
Not exactly:
* adds another dependency
* still uses more memory (relevant if you have 100s of models)
* has some [reserved property names](https://github.com/mobxjs/mobx-utils/blob/master/src/create-view-model.ts#L20) - I'm [trying to remove](https://github.com/infinum/datx) as much of the reserved names as possible (TBD)
