### ISSUE TITLE
MobX v4 support?

### ISSUE THREAD

**Issue by Overbryd** [infinum/mobx-jsonapi-store#80]
Seems to be broken.

```
Uncaught Error: [mobx] Passing a 'computed' as initial property value is no longer supported by extendObservable. Use a getter or decorator instead
```

**package.json:**

```
    "mobx": "^4.1.1",
    "mobx-jsonapi-store": "^4.2.1",
    "mobx-react": "^5.0.0",
    "mobx-react-router": "^4.0.2",
```

**Comment by DarkoKukovec** [comment]
That's correct. I need to update the readme, but adding MobX 4 support (without breaking MobX 3 support) would be very time consuming and since I was already finishing up the new library, [DatX](https://github.com/infinum/datx), that is taking over for both this lib and [mobx-collection-store](https://github.com/infinum/mobx-collection-store), I decided not to upgrade this lib and make DatX work only with MobX 4. If you decide to go forward with MobX 4 and DatX, there are [migration guides](https://github.com/infinum/datx/wiki/Migration-from-mobx-jsonapi-store) and also feel free to open an issue if you have any problems migrating or if you find any bugs (both in code and in docs).

The lib follows the same principles, but it has better TypeScript support (useful also if you're not using TypeScript since the editor will have much better suggestions) and it fixes some inconsistencies (especially in the naming).
